name: Deploy HMR to Ubuntu Server

on:
  push:
    branches: [ "main" ] # Cambia "main" a "master" si tu rama principal se llama así

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy via SSH
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          # 1. Entrar a la carpeta del proyecto en el servidor
          cd /home/jv/HMR
          
          # 2. Descargar los cambios más recientes de GitHub
          git pull origin main
          
          # 3. Reconstruir y levantar los contenedores de Docker
          docker compose up -d --build
          
          # 4. Limpiar imágenes Docker viejas para no llenar el disco de la VM
          docker image prune -f